language: node_js
node_js:
  - '10'

# Package has no tests for CI/CD
install: true
script: true

# 🚀 Semantic release
deploy:
  provider: script
  # Prevent Travis from resetting working directory after build
  skip_cleanup: true
  script: npx semantic-release
  on:
    branch: master
