name: CI/CD

# Run action on all PRS and on change to master branch in order to test PRs for
# continuous integration and deploy master for continuous deployment
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  skip:
    name: CI Skip
    if: contains(github.event.head_commit.message, 'skip ci')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI Commit
        run: echo "Skip CI commit success"
  test:
    name: Continuous Integration
    if: contains(github.event.head_commit.message, 'skip ci') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install
        run: CI=true npm install
      - name: Test
        run: npm test
  publish:
    name: Continuous Deployment
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install
        run: CI=true npm install
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_NPM_TOKEN }}
